name: Slack Notification Demo
on: 
  push:
jobs:
  slackNotification:
    name: Testing my bot outtttttttt
    runs-on: ubuntu-latest
    steps:
    - name: Notify slack
      env:
        SLACK_BOT_TOKEN: ${{ secrets.SLACK_WEBHOOK }}
      uses: pullreminders/slack-action@master
      with:
        args: '{\"channel\":\"C05ALHJN22F\",\"text\":\"Hello world this is me \"}'
